refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S %Z)} - {h({l})} - {m}{n}"
#  file:
#    kind: rolling_file
#    path: "/var/log/snapshoot/snapshoot.log"
#    policy:
#      kind: compound
#      trigger:
#        kind: time
#        interval: 1 day
#      roller:
#        kind: fixed_window
#        base: 1
#        count: 5
#        pattern: "snapshoot.{}.log"
#    encoder:
#      pattern: "{d(%Y-%m-%d %H:%M:%S %Z)} - {h({l})} - {m}{n}"
root:
  level: debug
  appenders:
    - stdout
#    - file
